### ISSUE TITLE
Mod not showing up ingame

### ISSUE THREAD

**Issue by DrMystic03** [TheTurkeyDev/BlockHighlighter#2]
![not working](https://user-images.githubusercontent.com/68919699/88700786-25dce100-d0d7-11ea-9110-61a205307194.png)
https://i.imgur.com/mf6BJdc.png
https://i.imgur.com/gB7p67Q.png 
I'm on 1.14.4 forge using quite a few other mods along side this, I don't think it has anything to do with the other mods as I still can't get anything to show up when I run the mod by itself.

**Comment by TheTurkeyDev** [comment]
Your second image shows that Custom selection box is off. Try setting that to on

**Comment by DrMystic03** [comment]
> Your second image shows that Custom selection box is off. Try setting that to on

No luck sadly :(

**Comment by TheTurkeyDev** [comment]
![Capture1](https://user-images.githubusercontent.com/2951505/88872671-b5be8000-d1e8-11ea-9af7-2dbe96fcc4df.PNG)
![Capture2](https://user-images.githubusercontent.com/2951505/88872674-b5be8000-d1e8-11ea-97f1-fe077c6bdab6.PNG)
This worked for me. Latest version and latest forge. What is your color set to?

**Comment by DrMystic03** [comment]
https://i.imgur.com/RUe5imL.png this is the version of forge im using 
this is the colors i selected (random) https://i.imgur.com/Z5igJxZ.png 
and this is the version of the mod i have installed https://i.imgur.com/oriQ9Hn.png

**Comment by TheTurkeyDev** [comment]
Not sure what I tell you man. I loaded up a fresh instance with your exact versions, set the colors to what you had and turned them on and it all works.

**Comment by DrMystic03** [comment]
Okay im honestly im a bit confused at this point. I deleted the mod and config file, redownloaded, loaded up, still wasn't working, thought about the texture pack messing it up so I turned my texture packs off, moved the mod resources bit up, it started working so I added my texture pack back in and moved it to the bottom again and its still working. Thanks for all the help and sorry i was probably just being stupid lol

**Comment by TheTurkeyDev** [comment]
Well, at least it's working!
